using System.Runtime.InteropServices;

namespace Ectn.Utilities.TemsInfo {

    /// <summary>
    /// The client uses the "Configuration" messages to define the messages
    /// that should be generated by the TEMS system over the current
    /// connection.
    /// </summary>
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    internal struct TemsInfoMsgConfiguration {

        /// <summary>
        /// Identification of the client.
        /// The TEMS system accepts only one connection with the same
        /// identification.
        /// </summary>
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 100)]
        public string clientIdentifier;

        /// <summary>
        /// Length of the following message part in bytes.
        /// </summary>
        public int clientConfigurationSize;
    }
}